package dataobjects

type Frame struct {
	Events []struct{}`json:"-"`
	ParticipantFrames struct {
		Num1 struct {
			ChampionStats struct {
				AbilityHaste         int `json:"abilityHaste"`
				AbilityPower         int `json:"abilityPower"`
				Armor                int `json:"armor"`
				ArmorPen             int `json:"armorPen"`
				ArmorPenPercent      int `json:"armorPenPercent"`
				AttackDamage         int `json:"attackDamage"`
				AttackSpeed          int `json:"attackSpeed"`
				BonusArmorPenPercent int `json:"bonusArmorPenPercent"`
				BonusMagicPenPercent int `json:"bonusMagicPenPercent"`
				CcReduction          int `json:"ccReduction"`
				CooldownReduction    int `json:"cooldownReduction"`
				Health               int `json:"health"`
				HealthMax            int `json:"healthMax"`
				HealthRegen          int `json:"healthRegen"`
				Lifesteal            int `json:"lifesteal"`
				MagicPen             int `json:"magicPen"`
				MagicPenPercent      int `json:"magicPenPercent"`
				MagicResist          int `json:"magicResist"`
				MovementSpeed        int `json:"movementSpeed"`
				Omnivamp             int `json:"omnivamp"`
				PhysicalVamp         int `json:"physicalVamp"`
				Power                int `json:"power"`
				PowerMax             int `json:"powerMax"`
				PowerRegen           int `json:"powerRegen"`
				SpellVamp            int `json:"spellVamp"`
			} `json:"championStats"`
			CurrentGold int `json:"currentGold"`
			DamageStats struct {
				MagicDamageDone               int `json:"magicDamageDone"`
				MagicDamageDoneToChampions    int `json:"magicDamageDoneToChampions"`
				MagicDamageTaken              int `json:"magicDamageTaken"`
				PhysicalDamageDone            int `json:"physicalDamageDone"`
				PhysicalDamageDoneToChampions int `json:"physicalDamageDoneToChampions"`
				PhysicalDamageTaken           int `json:"physicalDamageTaken"`
				TotalDamageDone               int `json:"totalDamageDone"`
				TotalDamageDoneToChampions    int `json:"totalDamageDoneToChampions"`
				TotalDamageTaken              int `json:"totalDamageTaken"`
				TrueDamageDone                int `json:"trueDamageDone"`
				TrueDamageDoneToChampions     int `json:"trueDamageDoneToChampions"`
				TrueDamageTaken               int `json:"trueDamageTaken"`
			} `json:"damageStats"`
			GoldPerSecond       int `json:"goldPerSecond"`
			JungleMinionsKilled int `json:"jungleMinionsKilled"`
			Level               int `json:"level"`
			MinionsKilled       int `json:"minionsKilled"`
			ParticipantID       int `json:"participantId"`
			Position            struct {
				X int `json:"x"`
				Y int `json:"y"`
			} `json:"position"`
			TimeEnemySpentControlled int `json:"timeEnemySpentControlled"`
			TotalGold                int `json:"totalGold"`
			Xp                       int `json:"xp"`
		} `json:"1"`
		Num2 struct {
			ChampionStats struct {
				AbilityHaste         int `json:"abilityHaste"`
				AbilityPower         int `json:"abilityPower"`
				Armor                int `json:"armor"`
				ArmorPen             int `json:"armorPen"`
				ArmorPenPercent      int `json:"armorPenPercent"`
				AttackDamage         int `json:"attackDamage"`
				AttackSpeed          int `json:"attackSpeed"`
				BonusArmorPenPercent int `json:"bonusArmorPenPercent"`
				BonusMagicPenPercent int `json:"bonusMagicPenPercent"`
				CcReduction          int `json:"ccReduction"`
				CooldownReduction    int `json:"cooldownReduction"`
				Health               int `json:"health"`
				HealthMax            int `json:"healthMax"`
				HealthRegen          int `json:"healthRegen"`
				Lifesteal            int `json:"lifesteal"`
				MagicPen             int `json:"magicPen"`
				MagicPenPercent      int `json:"magicPenPercent"`
				MagicResist          int `json:"magicResist"`
				MovementSpeed        int `json:"movementSpeed"`
				Omnivamp             int `json:"omnivamp"`
				PhysicalVamp         int `json:"physicalVamp"`
				Power                int `json:"power"`
				PowerMax             int `json:"powerMax"`
				PowerRegen           int `json:"powerRegen"`
				SpellVamp            int `json:"spellVamp"`
			} `json:"championStats"`
			CurrentGold int `json:"currentGold"`
			DamageStats struct {
				MagicDamageDone               int `json:"magicDamageDone"`
				MagicDamageDoneToChampions    int `json:"magicDamageDoneToChampions"`
				MagicDamageTaken              int `json:"magicDamageTaken"`
				PhysicalDamageDone            int `json:"physicalDamageDone"`
				PhysicalDamageDoneToChampions int `json:"physicalDamageDoneToChampions"`
				PhysicalDamageTaken           int `json:"physicalDamageTaken"`
				TotalDamageDone               int `json:"totalDamageDone"`
				TotalDamageDoneToChampions    int `json:"totalDamageDoneToChampions"`
				TotalDamageTaken              int `json:"totalDamageTaken"`
				TrueDamageDone                int `json:"trueDamageDone"`
				TrueDamageDoneToChampions     int `json:"trueDamageDoneToChampions"`
				TrueDamageTaken               int `json:"trueDamageTaken"`
			} `json:"damageStats"`
			GoldPerSecond       int `json:"goldPerSecond"`
			JungleMinionsKilled int `json:"jungleMinionsKilled"`
			Level               int `json:"level"`
			MinionsKilled       int `json:"minionsKilled"`
			ParticipantID       int `json:"participantId"`
			Position            struct {
				X int `json:"x"`
				Y int `json:"y"`
			} `json:"position"`
			TimeEnemySpentControlled int `json:"timeEnemySpentControlled"`
			TotalGold                int `json:"totalGold"`
			Xp                       int `json:"xp"`
		} `json:"2"`
		Num3 struct {
			ChampionStats struct {
				AbilityHaste         int `json:"abilityHaste"`
				AbilityPower         int `json:"abilityPower"`
				Armor                int `json:"armor"`
				ArmorPen             int `json:"armorPen"`
				ArmorPenPercent      int `json:"armorPenPercent"`
				AttackDamage         int `json:"attackDamage"`
				AttackSpeed          int `json:"attackSpeed"`
				BonusArmorPenPercent int `json:"bonusArmorPenPercent"`
				BonusMagicPenPercent int `json:"bonusMagicPenPercent"`
				CcReduction          int `json:"ccReduction"`
				CooldownReduction    int `json:"cooldownReduction"`
				Health               int `json:"health"`
				HealthMax            int `json:"healthMax"`
				HealthRegen          int `json:"healthRegen"`
				Lifesteal            int `json:"lifesteal"`
				MagicPen             int `json:"magicPen"`
				MagicPenPercent      int `json:"magicPenPercent"`
				MagicResist          int `json:"magicResist"`
				MovementSpeed        int `json:"movementSpeed"`
				Omnivamp             int `json:"omnivamp"`
				PhysicalVamp         int `json:"physicalVamp"`
				Power                int `json:"power"`
				PowerMax             int `json:"powerMax"`
				PowerRegen           int `json:"powerRegen"`
				SpellVamp            int `json:"spellVamp"`
			} `json:"championStats"`
			CurrentGold int `json:"currentGold"`
			DamageStats struct {
				MagicDamageDone               int `json:"magicDamageDone"`
				MagicDamageDoneToChampions    int `json:"magicDamageDoneToChampions"`
				MagicDamageTaken              int `json:"magicDamageTaken"`
				PhysicalDamageDone            int `json:"physicalDamageDone"`
				PhysicalDamageDoneToChampions int `json:"physicalDamageDoneToChampions"`
				PhysicalDamageTaken           int `json:"physicalDamageTaken"`
				TotalDamageDone               int `json:"totalDamageDone"`
				TotalDamageDoneToChampions    int `json:"totalDamageDoneToChampions"`
				TotalDamageTaken              int `json:"totalDamageTaken"`
				TrueDamageDone                int `json:"trueDamageDone"`
				TrueDamageDoneToChampions     int `json:"trueDamageDoneToChampions"`
				TrueDamageTaken               int `json:"trueDamageTaken"`
			} `json:"damageStats"`
			GoldPerSecond       int `json:"goldPerSecond"`
			JungleMinionsKilled int `json:"jungleMinionsKilled"`
			Level               int `json:"level"`
			MinionsKilled       int `json:"minionsKilled"`
			ParticipantID       int `json:"participantId"`
			Position            struct {
				X int `json:"x"`
				Y int `json:"y"`
			} `json:"position"`
			TimeEnemySpentControlled int `json:"timeEnemySpentControlled"`
			TotalGold                int `json:"totalGold"`
			Xp                       int `json:"xp"`
		} `json:"3"`
		Num4 struct {
			ChampionStats struct {
				AbilityHaste         int `json:"abilityHaste"`
				AbilityPower         int `json:"abilityPower"`
				Armor                int `json:"armor"`
				ArmorPen             int `json:"armorPen"`
				ArmorPenPercent      int `json:"armorPenPercent"`
				AttackDamage         int `json:"attackDamage"`
				AttackSpeed          int `json:"attackSpeed"`
				BonusArmorPenPercent int `json:"bonusArmorPenPercent"`
				BonusMagicPenPercent int `json:"bonusMagicPenPercent"`
				CcReduction          int `json:"ccReduction"`
				CooldownReduction    int `json:"cooldownReduction"`
				Health               int `json:"health"`
				HealthMax            int `json:"healthMax"`
				HealthRegen          int `json:"healthRegen"`
				Lifesteal            int `json:"lifesteal"`
				MagicPen             int `json:"magicPen"`
				MagicPenPercent      int `json:"magicPenPercent"`
				MagicResist          int `json:"magicResist"`
				MovementSpeed        int `json:"movementSpeed"`
				Omnivamp             int `json:"omnivamp"`
				PhysicalVamp         int `json:"physicalVamp"`
				Power                int `json:"power"`
				PowerMax             int `json:"powerMax"`
				PowerRegen           int `json:"powerRegen"`
				SpellVamp            int `json:"spellVamp"`
			} `json:"championStats"`
			CurrentGold int `json:"currentGold"`
			DamageStats struct {
				MagicDamageDone               int `json:"magicDamageDone"`
				MagicDamageDoneToChampions    int `json:"magicDamageDoneToChampions"`
				MagicDamageTaken              int `json:"magicDamageTaken"`
				PhysicalDamageDone            int `json:"physicalDamageDone"`
				PhysicalDamageDoneToChampions int `json:"physicalDamageDoneToChampions"`
				PhysicalDamageTaken           int `json:"physicalDamageTaken"`
				TotalDamageDone               int `json:"totalDamageDone"`
				TotalDamageDoneToChampions    int `json:"totalDamageDoneToChampions"`
				TotalDamageTaken              int `json:"totalDamageTaken"`
				TrueDamageDone                int `json:"trueDamageDone"`
				TrueDamageDoneToChampions     int `json:"trueDamageDoneToChampions"`
				TrueDamageTaken               int `json:"trueDamageTaken"`
			} `json:"damageStats"`
			GoldPerSecond       int `json:"goldPerSecond"`
			JungleMinionsKilled int `json:"jungleMinionsKilled"`
			Level               int `json:"level"`
			MinionsKilled       int `json:"minionsKilled"`
			ParticipantID       int `json:"participantId"`
			Position            struct {
				X int `json:"x"`
				Y int `json:"y"`
			} `json:"position"`
			TimeEnemySpentControlled int `json:"timeEnemySpentControlled"`
			TotalGold                int `json:"totalGold"`
			Xp                       int `json:"xp"`
		} `json:"4"`
		Num5 struct {
			ChampionStats struct {
				AbilityHaste         int `json:"abilityHaste"`
				AbilityPower         int `json:"abilityPower"`
				Armor                int `json:"armor"`
				ArmorPen             int `json:"armorPen"`
				ArmorPenPercent      int `json:"armorPenPercent"`
				AttackDamage         int `json:"attackDamage"`
				AttackSpeed          int `json:"attackSpeed"`
				BonusArmorPenPercent int `json:"bonusArmorPenPercent"`
				BonusMagicPenPercent int `json:"bonusMagicPenPercent"`
				CcReduction          int `json:"ccReduction"`
				CooldownReduction    int `json:"cooldownReduction"`
				Health               int `json:"health"`
				HealthMax            int `json:"healthMax"`
				HealthRegen          int `json:"healthRegen"`
				Lifesteal            int `json:"lifesteal"`
				MagicPen             int `json:"magicPen"`
				MagicPenPercent      int `json:"magicPenPercent"`
				MagicResist          int `json:"magicResist"`
				MovementSpeed        int `json:"movementSpeed"`
				Omnivamp             int `json:"omnivamp"`
				PhysicalVamp         int `json:"physicalVamp"`
				Power                int `json:"power"`
				PowerMax             int `json:"powerMax"`
				PowerRegen           int `json:"powerRegen"`
				SpellVamp            int `json:"spellVamp"`
			} `json:"championStats"`
			CurrentGold int `json:"currentGold"`
			DamageStats struct {
				MagicDamageDone               int `json:"magicDamageDone"`
				MagicDamageDoneToChampions    int `json:"magicDamageDoneToChampions"`
				MagicDamageTaken              int `json:"magicDamageTaken"`
				PhysicalDamageDone            int `json:"physicalDamageDone"`
				PhysicalDamageDoneToChampions int `json:"physicalDamageDoneToChampions"`
				PhysicalDamageTaken           int `json:"physicalDamageTaken"`
				TotalDamageDone               int `json:"totalDamageDone"`
				TotalDamageDoneToChampions    int `json:"totalDamageDoneToChampions"`
				TotalDamageTaken              int `json:"totalDamageTaken"`
				TrueDamageDone                int `json:"trueDamageDone"`
				TrueDamageDoneToChampions     int `json:"trueDamageDoneToChampions"`
				TrueDamageTaken               int `json:"trueDamageTaken"`
			} `json:"damageStats"`
			GoldPerSecond       int `json:"goldPerSecond"`
			JungleMinionsKilled int `json:"jungleMinionsKilled"`
			Level               int `json:"level"`
			MinionsKilled       int `json:"minionsKilled"`
			ParticipantID       int `json:"participantId"`
			Position            struct {
				X int `json:"x"`
				Y int `json:"y"`
			} `json:"position"`
			TimeEnemySpentControlled int `json:"timeEnemySpentControlled"`
			TotalGold                int `json:"totalGold"`
			Xp                       int `json:"xp"`
		} `json:"5"`
		Num6 struct {
			ChampionStats struct {
				AbilityHaste         int `json:"abilityHaste"`
				AbilityPower         int `json:"abilityPower"`
				Armor                int `json:"armor"`
				ArmorPen             int `json:"armorPen"`
				ArmorPenPercent      int `json:"armorPenPercent"`
				AttackDamage         int `json:"attackDamage"`
				AttackSpeed          int `json:"attackSpeed"`
				BonusArmorPenPercent int `json:"bonusArmorPenPercent"`
				BonusMagicPenPercent int `json:"bonusMagicPenPercent"`
				CcReduction          int `json:"ccReduction"`
				CooldownReduction    int `json:"cooldownReduction"`
				Health               int `json:"health"`
				HealthMax            int `json:"healthMax"`
				HealthRegen          int `json:"healthRegen"`
				Lifesteal            int `json:"lifesteal"`
				MagicPen             int `json:"magicPen"`
				MagicPenPercent      int `json:"magicPenPercent"`
				MagicResist          int `json:"magicResist"`
				MovementSpeed        int `json:"movementSpeed"`
				Omnivamp             int `json:"omnivamp"`
				PhysicalVamp         int `json:"physicalVamp"`
				Power                int `json:"power"`
				PowerMax             int `json:"powerMax"`
				PowerRegen           int `json:"powerRegen"`
				SpellVamp            int `json:"spellVamp"`
			} `json:"championStats"`
			CurrentGold int `json:"currentGold"`
			DamageStats struct {
				MagicDamageDone               int `json:"magicDamageDone"`
				MagicDamageDoneToChampions    int `json:"magicDamageDoneToChampions"`
				MagicDamageTaken              int `json:"magicDamageTaken"`
				PhysicalDamageDone            int `json:"physicalDamageDone"`
				PhysicalDamageDoneToChampions int `json:"physicalDamageDoneToChampions"`
				PhysicalDamageTaken           int `json:"physicalDamageTaken"`
				TotalDamageDone               int `json:"totalDamageDone"`
				TotalDamageDoneToChampions    int `json:"totalDamageDoneToChampions"`
				TotalDamageTaken              int `json:"totalDamageTaken"`
				TrueDamageDone                int `json:"trueDamageDone"`
				TrueDamageDoneToChampions     int `json:"trueDamageDoneToChampions"`
				TrueDamageTaken               int `json:"trueDamageTaken"`
			} `json:"damageStats"`
			GoldPerSecond       int `json:"goldPerSecond"`
			JungleMinionsKilled int `json:"jungleMinionsKilled"`
			Level               int `json:"level"`
			MinionsKilled       int `json:"minionsKilled"`
			ParticipantID       int `json:"participantId"`
			Position            struct {
				X int `json:"x"`
				Y int `json:"y"`
			} `json:"position"`
			TimeEnemySpentControlled int `json:"timeEnemySpentControlled"`
			TotalGold                int `json:"totalGold"`
			Xp                       int `json:"xp"`
		} `json:"6"`
		Num7 struct {
			ChampionStats struct {
				AbilityHaste         int `json:"abilityHaste"`
				AbilityPower         int `json:"abilityPower"`
				Armor                int `json:"armor"`
				ArmorPen             int `json:"armorPen"`
				ArmorPenPercent      int `json:"armorPenPercent"`
				AttackDamage         int `json:"attackDamage"`
				AttackSpeed          int `json:"attackSpeed"`
				BonusArmorPenPercent int `json:"bonusArmorPenPercent"`
				BonusMagicPenPercent int `json:"bonusMagicPenPercent"`
				CcReduction          int `json:"ccReduction"`
				CooldownReduction    int `json:"cooldownReduction"`
				Health               int `json:"health"`
				HealthMax            int `json:"healthMax"`
				HealthRegen          int `json:"healthRegen"`
				Lifesteal            int `json:"lifesteal"`
				MagicPen             int `json:"magicPen"`
				MagicPenPercent      int `json:"magicPenPercent"`
				MagicResist          int `json:"magicResist"`
				MovementSpeed        int `json:"movementSpeed"`
				Omnivamp             int `json:"omnivamp"`
				PhysicalVamp         int `json:"physicalVamp"`
				Power                int `json:"power"`
				PowerMax             int `json:"powerMax"`
				PowerRegen           int `json:"powerRegen"`
				SpellVamp            int `json:"spellVamp"`
			} `json:"championStats"`
			CurrentGold int `json:"currentGold"`
			DamageStats struct {
				MagicDamageDone               int `json:"magicDamageDone"`
				MagicDamageDoneToChampions    int `json:"magicDamageDoneToChampions"`
				MagicDamageTaken              int `json:"magicDamageTaken"`
				PhysicalDamageDone            int `json:"physicalDamageDone"`
				PhysicalDamageDoneToChampions int `json:"physicalDamageDoneToChampions"`
				PhysicalDamageTaken           int `json:"physicalDamageTaken"`
				TotalDamageDone               int `json:"totalDamageDone"`
				TotalDamageDoneToChampions    int `json:"totalDamageDoneToChampions"`
				TotalDamageTaken              int `json:"totalDamageTaken"`
				TrueDamageDone                int `json:"trueDamageDone"`
				TrueDamageDoneToChampions     int `json:"trueDamageDoneToChampions"`
				TrueDamageTaken               int `json:"trueDamageTaken"`
			} `json:"damageStats"`
			GoldPerSecond       int `json:"goldPerSecond"`
			JungleMinionsKilled int `json:"jungleMinionsKilled"`
			Level               int `json:"level"`
			MinionsKilled       int `json:"minionsKilled"`
			ParticipantID       int `json:"participantId"`
			Position            struct {
				X int `json:"x"`
				Y int `json:"y"`
			} `json:"position"`
			TimeEnemySpentControlled int `json:"timeEnemySpentControlled"`
			TotalGold                int `json:"totalGold"`
			Xp                       int `json:"xp"`
		} `json:"7"`
		Num8 struct {
			ChampionStats struct {
				AbilityHaste         int `json:"abilityHaste"`
				AbilityPower         int `json:"abilityPower"`
				Armor                int `json:"armor"`
				ArmorPen             int `json:"armorPen"`
				ArmorPenPercent      int `json:"armorPenPercent"`
				AttackDamage         int `json:"attackDamage"`
				AttackSpeed          int `json:"attackSpeed"`
				BonusArmorPenPercent int `json:"bonusArmorPenPercent"`
				BonusMagicPenPercent int `json:"bonusMagicPenPercent"`
				CcReduction          int `json:"ccReduction"`
				CooldownReduction    int `json:"cooldownReduction"`
				Health               int `json:"health"`
				HealthMax            int `json:"healthMax"`
				HealthRegen          int `json:"healthRegen"`
				Lifesteal            int `json:"lifesteal"`
				MagicPen             int `json:"magicPen"`
				MagicPenPercent      int `json:"magicPenPercent"`
				MagicResist          int `json:"magicResist"`
				MovementSpeed        int `json:"movementSpeed"`
				Omnivamp             int `json:"omnivamp"`
				PhysicalVamp         int `json:"physicalVamp"`
				Power                int `json:"power"`
				PowerMax             int `json:"powerMax"`
				PowerRegen           int `json:"powerRegen"`
				SpellVamp            int `json:"spellVamp"`
			} `json:"championStats"`
			CurrentGold int `json:"currentGold"`
			DamageStats struct {
				MagicDamageDone               int `json:"magicDamageDone"`
				MagicDamageDoneToChampions    int `json:"magicDamageDoneToChampions"`
				MagicDamageTaken              int `json:"magicDamageTaken"`
				PhysicalDamageDone            int `json:"physicalDamageDone"`
				PhysicalDamageDoneToChampions int `json:"physicalDamageDoneToChampions"`
				PhysicalDamageTaken           int `json:"physicalDamageTaken"`
				TotalDamageDone               int `json:"totalDamageDone"`
				TotalDamageDoneToChampions    int `json:"totalDamageDoneToChampions"`
				TotalDamageTaken              int `json:"totalDamageTaken"`
				TrueDamageDone                int `json:"trueDamageDone"`
				TrueDamageDoneToChampions     int `json:"trueDamageDoneToChampions"`
				TrueDamageTaken               int `json:"trueDamageTaken"`
			} `json:"damageStats"`
			GoldPerSecond       int `json:"goldPerSecond"`
			JungleMinionsKilled int `json:"jungleMinionsKilled"`
			Level               int `json:"level"`
			MinionsKilled       int `json:"minionsKilled"`
			ParticipantID       int `json:"participantId"`
			Position            struct {
				X int `json:"x"`
				Y int `json:"y"`
			} `json:"position"`
			TimeEnemySpentControlled int `json:"timeEnemySpentControlled"`
			TotalGold                int `json:"totalGold"`
			Xp                       int `json:"xp"`
		} `json:"8"`
		Num9 struct {
			ChampionStats struct {
				AbilityHaste         int `json:"abilityHaste"`
				AbilityPower         int `json:"abilityPower"`
				Armor                int `json:"armor"`
				ArmorPen             int `json:"armorPen"`
				ArmorPenPercent      int `json:"armorPenPercent"`
				AttackDamage         int `json:"attackDamage"`
				AttackSpeed          int `json:"attackSpeed"`
				BonusArmorPenPercent int `json:"bonusArmorPenPercent"`
				BonusMagicPenPercent int `json:"bonusMagicPenPercent"`
				CcReduction          int `json:"ccReduction"`
				CooldownReduction    int `json:"cooldownReduction"`
				Health               int `json:"health"`
				HealthMax            int `json:"healthMax"`
				HealthRegen          int `json:"healthRegen"`
				Lifesteal            int `json:"lifesteal"`
				MagicPen             int `json:"magicPen"`
				MagicPenPercent      int `json:"magicPenPercent"`
				MagicResist          int `json:"magicResist"`
				MovementSpeed        int `json:"movementSpeed"`
				Omnivamp             int `json:"omnivamp"`
				PhysicalVamp         int `json:"physicalVamp"`
				Power                int `json:"power"`
				PowerMax             int `json:"powerMax"`
				PowerRegen           int `json:"powerRegen"`
				SpellVamp            int `json:"spellVamp"`
			} `json:"championStats"`
			CurrentGold int `json:"currentGold"`
			DamageStats struct {
				MagicDamageDone               int `json:"magicDamageDone"`
				MagicDamageDoneToChampions    int `json:"magicDamageDoneToChampions"`
				MagicDamageTaken              int `json:"magicDamageTaken"`
				PhysicalDamageDone            int `json:"physicalDamageDone"`
				PhysicalDamageDoneToChampions int `json:"physicalDamageDoneToChampions"`
				PhysicalDamageTaken           int `json:"physicalDamageTaken"`
				TotalDamageDone               int `json:"totalDamageDone"`
				TotalDamageDoneToChampions    int `json:"totalDamageDoneToChampions"`
				TotalDamageTaken              int `json:"totalDamageTaken"`
				TrueDamageDone                int `json:"trueDamageDone"`
				TrueDamageDoneToChampions     int `json:"trueDamageDoneToChampions"`
				TrueDamageTaken               int `json:"trueDamageTaken"`
			} `json:"damageStats"`
			GoldPerSecond       int `json:"goldPerSecond"`
			JungleMinionsKilled int `json:"jungleMinionsKilled"`
			Level               int `json:"level"`
			MinionsKilled       int `json:"minionsKilled"`
			ParticipantID       int `json:"participantId"`
			Position            struct {
				X int `json:"x"`
				Y int `json:"y"`
			} `json:"position"`
			TimeEnemySpentControlled int `json:"timeEnemySpentControlled"`
			TotalGold                int `json:"totalGold"`
			Xp                       int `json:"xp"`
		} `json:"9"`
		Num10 struct {
			ChampionStats struct {
				AbilityHaste         int `json:"abilityHaste"`
				AbilityPower         int `json:"abilityPower"`
				Armor                int `json:"armor"`
				ArmorPen             int `json:"armorPen"`
				ArmorPenPercent      int `json:"armorPenPercent"`
				AttackDamage         int `json:"attackDamage"`
				AttackSpeed          int `json:"attackSpeed"`
				BonusArmorPenPercent int `json:"bonusArmorPenPercent"`
				BonusMagicPenPercent int `json:"bonusMagicPenPercent"`
				CcReduction          int `json:"ccReduction"`
				CooldownReduction    int `json:"cooldownReduction"`
				Health               int `json:"health"`
				HealthMax            int `json:"healthMax"`
				HealthRegen          int `json:"healthRegen"`
				Lifesteal            int `json:"lifesteal"`
				MagicPen             int `json:"magicPen"`
				MagicPenPercent      int `json:"magicPenPercent"`
				MagicResist          int `json:"magicResist"`
				MovementSpeed        int `json:"movementSpeed"`
				Omnivamp             int `json:"omnivamp"`
				PhysicalVamp         int `json:"physicalVamp"`
				Power                int `json:"power"`
				PowerMax             int `json:"powerMax"`
				PowerRegen           int `json:"powerRegen"`
				SpellVamp            int `json:"spellVamp"`
			} `json:"championStats"`
			CurrentGold int `json:"currentGold"`
			DamageStats struct {
				MagicDamageDone               int `json:"magicDamageDone"`
				MagicDamageDoneToChampions    int `json:"magicDamageDoneToChampions"`
				MagicDamageTaken              int `json:"magicDamageTaken"`
				PhysicalDamageDone            int `json:"physicalDamageDone"`
				PhysicalDamageDoneToChampions int `json:"physicalDamageDoneToChampions"`
				PhysicalDamageTaken           int `json:"physicalDamageTaken"`
				TotalDamageDone               int `json:"totalDamageDone"`
				TotalDamageDoneToChampions    int `json:"totalDamageDoneToChampions"`
				TotalDamageTaken              int `json:"totalDamageTaken"`
				TrueDamageDone                int `json:"trueDamageDone"`
				TrueDamageDoneToChampions     int `json:"trueDamageDoneToChampions"`
				TrueDamageTaken               int `json:"trueDamageTaken"`
			} `json:"damageStats"`
			GoldPerSecond       int `json:"goldPerSecond"`
			JungleMinionsKilled int `json:"jungleMinionsKilled"`
			Level               int `json:"level"`
			MinionsKilled       int `json:"minionsKilled"`
			ParticipantID       int `json:"participantId"`
			Position            struct {
				X int `json:"x"`
				Y int `json:"y"`
			} `json:"position"`
			TimeEnemySpentControlled int `json:"timeEnemySpentControlled"`
			TotalGold                int `json:"totalGold"`
			Xp                       int `json:"xp"`
		} `json:"10"`
	} `json:"participantFrames"`
}
